version: '3'
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  url:
    image: registry.cn-beijing.aliyuncs.com/maslow/nsfw_spider
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: node url.js -c 10 -w 10
    deploy:
      replicas: 1
    volumes:
      - ../data:/mnt/data

  img:
    image: registry.cn-beijing.aliyuncs.com/maslow/nsfw_spider
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: node img.js -c 10 -w 10
    deploy:
      replicas: 1
    volumes:
      - ../data:/mnt/data

  scanner:
    image: registry.cn-beijing.aliyuncs.com/maslow/nsfw_scanner
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: python classify_nsfw.py
    deploy:
      replicas: 1
    volumes:
      - ../data:/mnt/data

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  redis-data: