version: '3'
services:
  redis:
    image: redis:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  url:
    image: registry-vpc.cn-beijing.aliyuncs.com/maslow/nsfw_spider
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: node url.js
    deploy:
      replicas: 1
    volumes:
      - /mnt/data:/mnt/data

  img:
    image: registry-vpc.cn-beijing.aliyuncs.com/maslow/nsfw_spider
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: node img.js
    deploy:
      replicas: 1
    volumes:
      - /mnt/data:/mnt/data

  scanner:
    image: registry-vpc.cn-beijing.aliyuncs.com/maslow/nsfw_scanner
    environment:
      REDIS_HOST: redis
    working_dir: /app
    command: python classify_nsfw.py
    deploy:
      replicas: 1
    volumes:
      - /mnt/data:/mnt/data

volumes:
  redis-data: